# Site settings
title: Jack Harter - DevOps Engineer
description: DevOps and Linux Engineer portfolio showcasing professional experience, skills, and projects
author: Jack Harter
email: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hartr.net" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: pretty

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - docs/
  - .vscode/
  - .git/
  - .github/
  - README.md

# Include files that start with underscore or dot (if needed)
include:
  - _pages

# Collections (if needed in future)
collections:
  pages:
    output: true
    permalink: /pages/:name/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
    values:
      layout: "default"

# GitHub Pages compatibility
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Site navigation
navigation:
  - title: Home
    url: /
  - title: About the Author
    url: /pages/about/
  - title: Projects
    url: /pages/projects/
  - title: Contact
    url: /pages/contact/

# Social links
social:
  github: jharter1
  linkedin: jwharter
  blog: https://blog.hartr.net
  hackernews: jhartr
  linktree: jackharter
